name: Dependency Updates

on:
  push:
    branches: [ main ]

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '12.x'

    - name: Install Dependencies
      run: npm install

    - name: Check for outdated dependencies
      run: npm outdated

    - name: Update Dependencies
      run: npm update

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "Update dependencies" -a || echo "No changes to commit"

    - name: Push changes
      run: git push

 