name: Documentation Deployment

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'

jobs:
  deploy-docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and deploy documentation
      run: echo "Insert command to build and deploy documentation here"
