name: Scheduled Tasks

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight

jobs:
  maintenance:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '12.x'
    - run: npm install
    - run: npm start
